# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Locker < Formula
  desc "Store secrets on your local file system."
  homepage "https://github.com/lucasepe/locker"
  version "0.3.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/lucasepe/locker/releases/download/v0.3.0/locker_0.3.0_darwin_arm64.tar.gz"
      sha256 "218617254b24ee8a846f95a803b559a845715ac759fd3b590859923d119ccf30"

      def install
        bin.install "locker"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lucasepe/locker/releases/download/v0.3.0/locker_0.3.0_darwin_amd64.tar.gz"
      sha256 "fe15d27eb57f2fad460996b082c551839d6918072ccc880cdd6f6a8b443968dc"

      def install
        bin.install "locker"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/lucasepe/locker/releases/download/v0.3.0/locker_0.3.0_linux_amd64.tar.gz"
      sha256 "33a2f60bb0be389e5651f24f462d44c558452fc42f0886de6302e0355b0f796d"

      def install
        bin.install "locker"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lucasepe/locker/releases/download/v0.3.0/locker_0.3.0_linux_arm64.tar.gz"
      sha256 "1ae2c52ba73a051383a7159b6d8671f06e5fd444f5056c92d623020fcdbaec53"

      def install
        bin.install "locker"
      end
    end
  end
end
