# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Locker < Formula
  desc "Store secrets on your local file system."
  homepage "https://github.com/lucasepe/locker"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/lucasepe/locker/releases/download/v0.1.0/locker_0.1.0_darwin_arm64.tar.gz"
      sha256 "801c356298fdf71beda7545d1e522cf20bb722f4a02117df4ae9c2d9134acb5a"

      def install
        bin.install "locker"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lucasepe/locker/releases/download/v0.1.0/locker_0.1.0_darwin_amd64.tar.gz"
      sha256 "fac140a562c3a6f3ea601afc701f23a92f67bce3de61e4ca7057eeec43eb2740"

      def install
        bin.install "locker"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lucasepe/locker/releases/download/v0.1.0/locker_0.1.0_linux_arm64.tar.gz"
      sha256 "3bc7c2472e6ee96bffc6310432ce3232249e3d918e106eef53f91afe55f23629"

      def install
        bin.install "locker"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lucasepe/locker/releases/download/v0.1.0/locker_0.1.0_linux_amd64.tar.gz"
      sha256 "c6548cbb943ecd558595283ebcee573b216e0bab426f06c30dc27247200a4608"

      def install
        bin.install "locker"
      end
    end
  end
end
